import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
    paddingTop: 60,
    paddingHorizontal: 16,
  },
  topbar: {
    marginTop: -10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 40,
    borderColor: 'white',
    marginVertical: 2,
    borderRadius: 2,
    marginBottom: 10,
    paddingHorizontal: 8,
  },
  hamburger: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bar: {
    width: 24,
    height: 3,
    backgroundColor: '#fff',
    marginVertical: 2,
    borderRadius: 2,
  },
  header: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  body: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bodyText: {
    color: '#fff',
    fontSize: 18,
    width: 300,
    textAlign: 'center',
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 75,
    marginBottom: 20,
  },
  flipCard: {
    width: 160,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    backfaceVisibility: 'hidden',
  },
  front: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 160,
    height: 200,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  back: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 160,
    height: 200,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  editCircle: {
    width: 120,
    height: 120,
    borderRadius: 75,
    backgroundColor: '#1db954',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  pencil: {
    fontSize: 36,
    color: '#fff',
  },
  input: {
    width: 300,
    borderWidth: 1,
    borderColor: '#1db954',
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
    color: '#fff',
    backgroundColor: '#222',
    fontSize: 16,
  },
  saveBtn: {
    marginTop: 12,
    backgroundColor: '#1db954',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 18,
  },
  saveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  errorText: {
    color: 'white',
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  barLong: {
    marginTop: 20,
    width: 300,
    height: 3,
    backgroundColor: '#fff',
    marginVertical: 2,
    borderRadius: 2,
  },
});

export default styles;
